// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package config

import (
	"github.com/spf13/viper"
)

// Injectors from injector.go:

func Build() (*viper.Viper, func(), error) {
	viperViper, cleanup, err := Provider()
	if err != nil {
		return nil, nil, err
	}
	return viperViper, func() {
		cleanup()
	}, nil
}
