// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/spf13/viper"
)

// Injectors from injector.go:

// Build returns spf13/viper instance with resolved dependencies
func Build() (*viper.Viper, func(), error) {
	viperViper, cleanup, err := Provider()
	if err != nil {
		return nil, nil, err
	}
	return viperViper, func() {
		cleanup()
	}, nil
}
