// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package auth

import (
	"github.com/aristat/golang-example-app/app/config"
)

// Injectors from injector.go:

func Build() (*Middleware, func(), error) {
	viper, cleanup, err := config.Provider()
	if err != nil {
		return nil, nil, err
	}
	authConfig, cleanup2, err := ProviderCfg(viper)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	middleware, cleanup3, err := Provider(authConfig)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return middleware, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

func BuildTest() (*Middleware, func(), error) {
	middleware, cleanup, err := ProviderTest()
	if err != nil {
		return nil, nil, err
	}
	return middleware, func() {
		cleanup()
	}, nil
}
